import type { Metadata } from "next";
import "./globals.css";
import { IBM_Plex_Mono } from '@next/font/google';

const plexMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-plex-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plexMono.variable} antialiased bg-[#0D0C21]`}
      >
        {children}
      </body>
    </html>
  );
}
